/**
    * desc: You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Example 1: =>
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    
    Example 2: =>
    Input: s = "", t = "y"
    Output: "y"
    
    Constraints: =>
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
 */

/**
 *
 * @param s string
 * @param t string
 * @returns string
 */
const findTheDifferenceHash = (s: string, t: string): string => {
	const hashTable1: Record<string, number> = {};
	const hashTable2: Record<string, number> = {};

	for (let i = 0; i < t.length; i++) {
		if (i < s.length) {
			if (hashTable1[s[i]] === undefined) hashTable1[s[i]] = 0;
			hashTable1[s[i]] += 1;
		}

		if (hashTable2[t[i]] === undefined) hashTable2[t[i]] = 0;
		hashTable2[t[i]] += 1;
	}

	for (let [key, value] of Object.entries(hashTable2)) {
		if ((hashTable1[key] ?? 0) < value) return key;
	}

	return '';
};

const findTheDifferenceSort = (s: string, t: string): string => {
	s = s.split('').sort().join('');
	t = t.split('').sort().join('');

	for (let i = 0; i < t.length; i++) {
		if (s[i] !== t[i]) return t[i];
	}

	return '';
};
